const GET_ALL_FARMS_START = 'GET_ALL_FARMS_START';
const GET_ALL_FARMS_SUCCEED = 'GET_ALL_FARMS_SUCCEED';
const GET_ALL_FARMS_FAIL = 'GET_ALL_FARMS_FAIL';

const POST_NEW_FARM_START = 'POST_NEW_FARM_START';
const POST_NEW_FARM_SUCCEED = 'POST_NEW_FARM_SUCCEED';
const POST_NEW_FARM_FAIL = 'POST_NEW_FARM_FAIL';

const PUT_NEW_CONTRIBUTION_START = 'PUT_NEW_CONTRIBUTION_START';
const PUT_NEW_CONTRIBUTION_SUCCEED = 'PUT_NEW_CONTRIBUTION_SUCCEED';
const PUT_NEW_CONTRIBUTION_FAIL = 'PUT_NEW_CONTRIBUTION_FAIL';


export default {
  GET_ALL_FARMS_START,
  GET_ALL_FARMS_SUCCEED,
  GET_ALL_FARMS_FAIL,
  POST_NEW_FARM_START,
  POST_NEW_FARM_SUCCEED,
  POST_NEW_FARM_FAIL,
  PUT_NEW_CONTRIBUTION_START,
  PUT_NEW_CONTRIBUTION_SUCCEED,
  PUT_NEW_CONTRIBUTION_FAIL,
} as const;
